# Generated by Django 4.2.6 on 2023-10-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='massa_kg',
            field=models.CharField(max_length=50),
        ),
    ]
