# Generated by Django 4.2.6 on 2023-10-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_alter_planet_massa_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='distancia_media_ao_sol_km',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='planet',
            name='periodo_orbital_dias',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='planet',
            name='temperatura_media_celsius',
            field=models.CharField(max_length=50),
        ),
    ]
