# Generated by Django 4.2.6 on 2023-10-07 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_alter_planet_distancia_media_ao_sol_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distanciaentreplanetas',
            name='tarifa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('time', models.TimeField()),
                ('arriving', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='trips_of_arriving', to='travel.planet')),
                ('departure', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='trips_of_departure', to='travel.planet')),
            ],
        ),
    ]
