# Generated by Django 4.2.5 on 2023-10-08 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_distanciaentreplanetas_tarifa_travel'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='itinerary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='places_to_visit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='recommendations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
