# Generated by Django 4.2.5 on 2023-09-28 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('diametro_km', models.FloatField()),
                ('massa_kg', models.FloatField()),
                ('distancia_media_ao_sol_km', models.FloatField()),
                ('periodo_orbital_dias', models.FloatField()),
                ('temperatura_media_celsius', models.FloatField()),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DistanciaEntrePlanetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distancia_km', models.FloatField()),
                ('planeta_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distancias_destino', to='planeta.planeta')),
                ('planeta_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distancias_partida', to='planeta.planeta')),
            ],
        ),
    ]
